import Head from 'next/head'

import {GraphQLClient, gql} from 'graphql-request';

const graphcms = new GraphQLClient("https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clfqzk5vm0l5l01up5df14lyn/master");

const QUERY = gql`
{
  articles {
    title
    slug
  }
}
`;

export async function getStaticProps(){
  const {articles} = await graphcms.request(QUERY);
  return {
    props: {
      articles,
    },
    revalidate: 10
  }
}

export default function Home({articles}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <h1 className='bg-green-700 py-4 text-center font-bold text-2xl text-white'>Orlęta Kielce</h1>
      {articles ? articles.map(article=> <p>{article.title}</p>) : 'loading...'}
    </main>
    </>
  )
}
